### ISSUE TITLE
about obstacle

### ISSUE THREAD

**Issue by EDITH666** [jviquerat/lbm#17]
hi，I‘m a beginner of LBM，i want to ask u a basic question, if i want to change the type of the obstacle how can i define my program, after trying several times,it is still something wrong in shape_type.

**Comment by jviquerat** [comment]
Hi, could you elaborate on your issue ?
Please provide an example of what you're trying to do and what error message you get

**Comment by EDITH666** [comment]
I have 2 questions
1）If I want to add a property of deflection angle in the Obstacle class, for example, if I want the initialized square object to have a deflection angle of 60 degrees, how should I modify the program?In my previous attempt, I tried to add a property of type 'angle' in the Obstacle class and made the necessary changes in the subsequent program, but the drawn shape did not deflect。

**Comment by EDITH666** [comment]
2）How can I remove the type restriction on the Obstacle class? For example, if I want to simulate irregular shapes, can I simply remove the type parameter

**Comment by jviquerat** [comment]
@EDITH666 you should check and modify the `src/utils/shapes.py` file to implement your modifications

**Comment by EDITH666** [comment]
thanks for your answer!

**Comment by EDITH666** [comment]
Excuse me to ask another question, I changed the maximum simulation time during simulation but the generated picture did not change What is the reason for this (is it to modify the t variable in the lattice file)

**Comment by jviquerat** [comment]
It all depends on the case you are considering, if you are run a low-reynolds case it is likely that the flow pattern converges to a static solution
